---
#####################
# Install Python
#####################

- hosts: all
  gather_facts: false # As Python is not yet installed, we cannot gather host facts

  tasks:
    - name: Update apt cache
      raw: "apt-get update"
      become: true
      changed_when: false

    - name: Install Python3
      raw: "apt-get -y -q install python3"
      become: true
      retries: 10
      delay: 20

    - name: Ensure 'python' command points to Python3
      raw: "apt-get -y -q install python-is-python3"
      become: true
      retries: 10
      delay: 20
#######################
# Setup K8s components
#######################

- hosts: etcd
  roles:
    - common
    - etcd

- hosts: controller
  roles:
    - common
    - controller

- hosts: worker
  roles:
    - common
    - worker
